### ISSUE TITLE
Benchmark / Stress Test ?

### ISSUE THREAD

**Issue by stuaxo** [brockwhittaker/AltCanvas#1]
I can see at least one place where it should be possible to optimise this, but first would it be possible to provide some sort of benchmark / stress test?

That way it will be possible to know if optimisations actually improve things.

I'd imagine some sort of test harness that does something like - set the random seed to a known value, then draw 1000 random rectangles, do the same for 10000 pixels.  + time both.

**Comment by brockwhittaker** [comment]
I just pushed an update with benchmark indicators. All stats are going to be under `Canvas.executeTime`. The biggest issue that you'll find however is that the overwhelming majority of render time comes from the DOM interpreting the base64 string (on average 80% of render time). The process of actually collecting input, adding it to the array, formatting it, and creating the entire BMP takes around 5ms in the demo. The image takes 35ms on average to load after putting it into the `img` src.

Another note is that the render time is theoretically flat. Since the entire BMP is recreated every time (no parts are just transferred over to the new BMP), it takes the same amount of time to render a completely noisy image (eg. `rgb(Math.random(), ..., ...)`), and a white background.

Knowing that, if you have any ideas for optimization let me know!

**Comment by brockwhittaker** [comment]
Actually on second looks, it appears as though data formatting does take up a lot of the time (up to 60%). Looks like there can definitely be some changes for efficiency in there.

**Comment by stuaxo** [comment]
Cool .. how do I interpret these numbers .. ?

main.js:34 Object {start: 1445710069661, dataFormatted: 1445710069670, fileCreated: 1445710069674, end: 1445710069691, total: 30}

**Comment by brockwhittaker** [comment]
They are just date stamps that are activated at the end of each step. Subtract them out to find the ms between steps.

**Comment by stuaxo** [comment]
Hmmm ... the main way to speed this up would be to base64 encode the 24 bit pixel color, then directly put this into the array that will be used by displayImage.

https://en.wikipedia.org/wiki/Base64
"Base64 encoding converts three octets into four encoded characters."
- base64 the 24 bit pixel value
- work out the offset into the array by using X, Y and then add the size of the bmp header
- copy that string into the array (multiple times if doing one line of a rectangle).

**Comment by brockwhittaker** [comment]
Base64 is already being used to display the images in the tags. What would be more efficient about this?

**Comment by stuaxo** [comment]
So I had a go at pre-making the base64 "pixels"...  and adding these to the end of this.file, but it seemed to slow things down... I guess all the calls to btoa were more of an overhead.

You could add stuff like dirty rect tracking, but I'm not sure it would speed things up.

So this your code is pretty fast already :D so I'll close this.
